### ISSUE TITLE
Running script with Sudo gives errors about .config directory

### ISSUE THREAD

**Issue by appleplectic** [mahboobkarimian/mbp-16-audio-install#1]
Running `sudo bash install.sh` tries to put the files `default.pa` and `daemon.conf` in `/root`, since sudo's home directory is different.

**Comment by mahboobkarimian** [comment]
Do not run `sudo bash install.sh`, I've put `sudo` inside the script so that you can just run `bash install.sh` it will prompt for a root password.
By the way, I will edit the script to remove `sudo` for the two files you mentioned as `sudo` is not needed for them.
